    global:
      scrape_interval:     15s
      evaluation_interval: 15s

    scrape_configs:
      - job_name: 'spring-boot-productos'
        metrics_path: '/management/prometheus'
        static_configs:
          - targets: ['localhost:8080']
            labels:
              application: 'productos-ms'
